# Before running, go to https://www.plex.tv/claim and PLEX_CLAIM=claim-...

services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - /pvr/plex/config:/config
      - /dev/shm/transcode:/transcode
      - /pvr/plex/data:/data
    network_mode: host
    restart: always
    environment:
      TZ: America/New_York
      PLEX_UID: 1000
      PLEX_GID: 1000
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility
      NVIDIA_VISIBLE_DEVICES: all
      CUDA_DRIVER_CAPABILITIES: compute,video,utility
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    cpu_shares: 1024

  vpn:
    image: dperson/openvpn-client
    container_name: vpn
    ports:
      - 5800:5800
      - 5900:5900
    volumes:
      - /pvr/openvpn:/vpn
    environment:
      TZ: America/New_York
      FIREWALL: ""
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    cpu_shares: 512

  tixati:
    image: appleman999/tixati
    container_name: tixati
    depends_on:
      vpn:
        condition: service_healthy
    restart: always
    environment:
      TZ: America/New_York
      DISPLAY_WIDTH: 1500
      DISPLAY_HEIGHT: 1000
      DARK_MODE: enabled
    volumes:
      - /pvr/tixati/config:/config
      - /pvr/plex/data:/plex
      - /pvr/tixati/torrents:/torrents
    network_mode: service:vpn
    cpu_shares: 512

